### ISSUE TITLE
Introduce a mechanism to handle CPU-intensive workloads

### ISSUE THREAD

**Issue by dlecocq** [seomoz/qless-js#32]
We've recently been bitten by event loop starvation in one of our CPU-intensive jobs. Mostly the problem for us is that the `Job.heartbeatUntilPromise` method doesn't work properly while doing the CPU-intensive work, so the job gets marked as stalled. In turn, it gets picked up by another worker, and the problem cascades.

One design I thought about was to move the job popping to the parent process, and pass them down to the existing child processes. Then the parent process could call `Job.heartbeatUntilPromise` for each of those handed-out jobs. However, that wouldn't solve the problem of jobs in the same child worker process from causing starvation for each other.

Our workload is such that at least for now, some of our jobs are CPU-bound and some are IO-bound, and we don't yet have the volume that it makes sense to run these queues on different servers. So I've also been thinking about adding some sort of `Job.fork()` method that could be called in the job code, which would `fork` off a new process to run this particular job. Behind the scenes it would probably use the same `workerpool` utility that `qless-js` uses already for the forking worker.

@b4hand @evanbattaglia thoughts?

**Comment by evanbattaglia** [comment]
It's been I while since I've look at qless-js so I'm not sure I have much to offer to the discussion. Your idea(s) sound reasonable. One thing that comes to mind is that you'd probably want to limit the number of CPU-intensive jobs you do on one machine. I wonder if your first idea about the parent process doing the `Job.heartbeatUntilPromise` would work if you ran two types of workers -- one processing one processing the IO-bound jobs and only the CPU-bound jobs (with a fixed number of worker processes) -- and limited the CPU-bound workers to one concurrent job per worker process?

BTW, @b4hand is on vacation so may not respond for another week and a half :)
